propeller:
  rawoutput-prefix: s3://my-s3-bucket/
  metadata-prefix: metadata/propeller
  workers: 4
  max-workflow-retries: 30
  workflow-reeval-duration: 30s
  downstream-eval-duration: 30s
  limit-namespace: "all"
  prof-port: 10254
  metrics-prefix: flyte
  enable-admin-launcher: true
  leader-election:
    lock-config-map:
      name: propeller-leader
      namespace: flyte
    enabled: true
    lease-duration: 15s
    renew-deadline: 10s
    retry-period: 2s
  queue:
    type: batch
    batching-interval: 2s
    batch-size: -1
    queue:
      type: maxof
      rate: 100
      capacity: 1000
      base-delay: 5s
      max-delay: 120s
    sub-queue:
      type: bucket
      rate: 10
      capacity: 100
  webhook:
    certDir: /etc/webhook/certs
    name: flyte-pod-webhook
